name: main
on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      
      - name: Get Node version
        id: node-version
        run: echo "version=$(node -v)" >> $GITHUB_OUTPUT

      - name: Install Dependencies
        run: |
          npm ci

      - name: Run tests
        run: npm run lint

      - name: Build
        run: npm run build